spring:
  application:
    name: email
  mail:
    host: smtp.gmail.com
    port: 587
    username: jzen.soft
    password: twfkjqqvtiivawoc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true